# Generated by Django 4.0.1 on 2023-11-15 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0012_alter_profile_usertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='district',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='divison',
        ),
    ]
